name: Deploy Staging

on:
  workflow_run:
    workflows: [Chromatic]
    branch: [main]
    types: [completed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@master
      - name: Recognize sha ref
        id: sharef
        run: |
          if [ "$EVENT" == 'pull_request' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.pull_request.head.sha}})"
          elif [ "$EVENT" == 'workflow_run' ]
          then
            echo "::set-output name=sha::$(echo ${{github.event.workflow_run.head_sha}})"
          else
            echo "::set-output name=sha::$(echo $GITHUB_SHA)"
          fi
        env:
          EVENT: ${{ github.event_name }}
          REF: ${{ github.ref }}
      - name: Commit Action Status
        uses: LouisBrunner/checks-action@v1.1.1
        with:
          name: ${{ steps.sharef.outputs.sha }}
          token: ${{ secrets.GITHUB_TOKEN }}
      # - uses: actions/setup-node@v3
      #   with:
      #     node-version-file: ".nvmrc"
      # - name: Run deploy script
      #   run: sleep 300 # TODO: Replace with actual deploy script
